fixing CI / CD with allure

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -8,8 +8,8 @@ on:
 
 jobs:
   test:
-    timeout-minutes: 60
     runs-on: ubuntu-latest
+    timeout-minutes: 60
 
     steps:
       - name: Checkout repository
@@ -26,18 +26,24 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Run Playwright tests
+      - name: Run Playwright Tests
         run: npx playwright test
         continue-on-error: true
 
-      - name: Generate Allure Report
+      - name: Debug Allure Results
         run: |
-          npm install -g allure-commandline
-          allure generate allure-results --clean -o allure-report
+          echo "Checking allure-results folder"
+          ls -la allure-results || echo "allure-results not found"
+
+      - name: Install Allure CLI
+        run: npm install -g allure-commandline
+
+      - name: Generate Allure Report
+        run: allure generate allure-results --clean -o allure-report
 
       - name: Upload Allure Report
-        uses: actions/upload-artifact@v4
         if: always()
+        uses: actions/upload-artifact@v4
         with:
           name: allure-report
           path: allure-report
